### ISSUE TITLE
Rename mediaSettingsRange "current" to "value"

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-image#106] opened 2016-10-13 09:31 UTC
I believe it makes more sense to have a `value` instead of `current` as most web developers are already familiar with `<input type="range">` element which includes already `min` and `max`.

``` diff
        interface MediaSettingsRange {
            readonly attribute long max;
            readonly attribute long min;
-            readonly attribute long current;
+            readonly attribute long value;
        };
```

**Comment by beaufortfrancois** [comment] 2016-10-17 12:20
I understand why from a UVC point of view, it is easier to call it `current`, but from the Web Developer side, I believe `value` is more suitable.

**Comment by beaufortfrancois** [comment] 2016-10-17 19:49
@miguelao And here's a Chromium PR for it: https://codereview.chromium.org/2427663002/

**Comment by miguelao** [comment] 2016-10-19 16:15
On the CL: thanks! No need to cut that deep though, we can just rename the .idl member.
I'm OK with this and will implement if @gmandyam agrees as well.

**Comment by beaufortfrancois** [comment] 2016-10-27 12:29
gentle ping @gmandyam

**Comment by gmandyam** [comment] 2016-10-27 19:39
@miguelao, @beaufortfrancois 

Assume you have also confirmed with Mozilla implementers.  I am OK with change as well.

**Comment by beaufortfrancois** [comment] 2016-10-28 12:48
@alfredoyang Does that look good on your side? I'm happy to provide a CL if needed.

**Comment by miguelao** [comment] 2017-03-28 14:40
With the latest changes, the "current" status of a control should be retrieved via [`MediaStreamTrack.getSettings()`](https://w3c.github.io/mediacapture-image/#mediatracksettings-section).   

This still leaves two uses of `MediaSettingsRange.current` within [`PhotoCapabilities`](https://w3c.github.io/mediacapture-image/#photocapabilities), namely those for `imageWidth` and `imageHeight`, but IMHO those can be removed as well, since the currently used width/height can and should be inspected in the captured Photo.

IOW I think we could drop all thoughts for `MediaSettingsRange.current`, which is anyway not in this Spec, and remove it from [`Chromium`](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/imagecapture/MediaSettingsRange.idl?q=mediasettingsrange.idl&sq=package:chromium&dr&l=12) as well.  @beaufortfrancois , does this SGTY?

**Comment by miguelao** [comment] 2017-03-29 16:45
Going to preventively close this issue because of my [previous comment](https://github.com/w3c/mediacapture-image/issues/106#issuecomment-289791869), @beaufortfrancois , shout/reopen if this surprises you.

**Closed by miguelao** 2017-03-29 16:45 UTC
Labels: renaming

**Comment by beaufortfrancois** [comment] 2017-03-30 07:02
👍 

Let's remove `MediaSettingsRange.current` from Chromium!

**Comment by miguelao** [comment] 2017-03-31 16:25
https://crbug.com/707262 for tracking purposes.
