### ISSUE TITLE
Need to capture unique frames

### ISSUE THREAD

**Issue by ds-hwang** [w3c/mediacapture-image#9] opened 2015-03-04 15:54 UTC
currently Mediastream Image Capture spec is just convenient utility which we can do same thing by CanvasElement.

For `takePhoto()` example,
```
navigator.getUserMedia({video: true}, gotMedia, failedToGetMedia);

function gotMedia(mediastream) {
   //Extract video track.
   var videoDevice = mediastream.getVideoTracks()[0];
   // Check if this device supports a picture mode...
   var captureDevice = new ImageCapture(videoDevice);
   if (captureDevice) {
         if (captureDevice.photoCapabilities.redEyeReduction) {
            captureDevice.setOptions({redEyeReductionSetting:true}).then(captureDevice.takePhoto().then(showPicture(blob),function(error){alert("Failed to take photo");}));
            }
         else
            console.log('No red eye reduction');
         }
     }

 function showPicture(e) {
    var img = document.querySelector("img");
    img.src = URL.createObjectURL(e.data);
    }
```

we can do `takePhoto()` by canvas element as follows
```
var canvasContext = document.createElement("canvas").getContext("2d");
navigator.mediaDevices.getUserMedia({
  video: true
}).then(function (stream) {
  // wire the stream into a <video> element for playback
  var video = document.querySelector('#video');
  video.srcObject = stream;
  video.play();

  video.onloadedmetadata = function () {
      canvasContext.drawImage(video);
      var img = document.querySelector("img");
      img.src = URL.createObjectURL(canvasContext.toDataUrl());
  };
}).catch(function (reason) {
  // handle gUM error here
});
```

For `grabFrame()` case,
```
var canvas = document.getElementById('frame');
navigator.getUserMedia({video: true}, gotMedia, failedToGetMedia);

function gotMedia(mediastream) {
   //Extract video track.  
   var videoDevice = mediastream.getVideoTracks()[0];
   // Check if this device supports a picture mode...
   var captureDevice = new ImageCapture(videoDevice);
   var frameVar;
   if (captureDevice) {
         frameVar = setInterval(captureDevice.grabFrame().then(processFrame()), 1000);
         }
     }

 function processFrame(e) {
     imgData = e.imageData;
     canvas.width = imgData.width;
     canvas.height = imgData.height;
     canvas.getContext('2d').drawImage(imgData, 0, 0,imgData.width,imgData.height);
     }
```

we can also do `grabFrame()` by canvas element as follows
```
var canvasContext = document.createElement("canvas").getContext("2d");
navigator.mediaDevices.getUserMedia({
  video: true
}).then(function (stream) {
  // wire the stream into a <video> element for playback
  var video = document.querySelector('#video');
  video.srcObject = stream;
  video.play();

  video.onloadedmetadata = function () {
      setInterval(processFrame(), 1000);
      function processFrame() {
        canvasContext.drawImage(video);
        var imgData = canvasContext.getImageData(0, 0, w, h);

       canvas.width = imgData.width;
       canvas.height = imgData.height;
       canvas.getContext('2d').drawImage(imgData, 0, 0,imgData.width,imgData.height);
      }
  };
}).catch(function (reason) {
  // handle gUM error here
});
```

I propose unique value this spec should provide. Currently, there is no way for javascript to grab unique video frames.
The examples in this spec uses brute-force `setInterval` to grab different frames.
`grabFrame()` should be changed to `grabFrames()` and event is emitted for all unique video frame.
The example will be supposed to be
```
var canvas = document.getElementById('frame');
navigator.getUserMedia({video: true}, gotMedia, failedToGetMedia);

function gotMedia(mediastream) {
   //Extract video track.  
   var videoDevice = mediastream.getVideoTracks()[0];
   // Check if this device supports a picture mode...
   var captureDevice = new ImageCapture(videoDevice);
   var frameVar;
   if (captureDevice) {
         frameVar = captureDevice.grabFrames().then(processFrame(e));
         }
     }

 // this callback is called per every video frame.
 function processFrame(e) {
     imgData = e.imageData;
     canvas.width = imgData.width;
     canvas.height = imgData.height;
     canvas.getContext('2d').drawImage(imgData, 0, 0,imgData.width,imgData.height);
     }
```

**Comment by anssiko** [comment] 2015-03-09 11:46
I think you should investigate whether the proposed `grabFrames()` should return a [`ReadableStream`](https://streams.spec.whatwg.org/#rs-class) per [guidance](http://www.w3.org/2001/tag/doc/promises-guide#streaming-data). For one-and-done operations, returning a `Promise` [does not work](http://www.w3.org/2001/tag/doc/promises-guide#when-not-to-use).

**Comment by gmandyam** [comment] 2015-03-09 19:03
>currently Mediastream Image Capture spec is just convenient utility which we can do same thing by CanvasElement.

This is inaccurate; takePhoto() is more of a camera API.  The photo settings that are applied for ImageCapture are not present for MediaStreams, much less for arbitrary video playing in an HTMLMediaElement.  For instance, the example that was cited in the current spec deals with red eye reduction as a precursor to taking the photo.  There is not even a check in the canvas capture example provided in the posted issue for whether the camera red eye reduction is set.  

> The examples in this spec uses brute-force setInterval to grab different frames.
grabFrame() should be changed to grabFrames() and event is emitted for all unique video frame.

There was a method in the original spec entitled frameGrabber (see https://lists.w3.org/Archives/Public/public-media-capture/2013Mar/0019.html), which was intended to do address the issues regarding callback efficiency with setInterval (which are somewhat analogous to the callback efficiency issues that resulted in the standardization of getAnimationFrame).  

The group decided that there were issues with implementation, and decided not to go that route. I don't  see a need at this point to re-open this topic.  You may also consider whether repeated frame/image capture could be better handled within a Service Worker context.

**Comment by gmandyam** [comment] 2016-09-14 15:38
@ds-hwang  - Closing issue as there has been no comment on this topic in over a year.  Please reopen if you feel it should be reconsidered.

**Closed by gmandyam** 2016-09-14 15:38 UTC

**Comment by developer239** [comment] 2018-01-14 18:01
@gmandyam 
#197 When I saw that this was proposed 3 years ago I was really happy before I realized that it is not implemented because you closed the issue. 😄 

I am writing `electron` application.

I need to get a nodejs **buffer of each frame** so that I can process it in opencv.

I need to do it real time.

I spent hours trying to figure out how should I get the frames. It feels like right now there isn't a way to read `MediaStream` as `readable stream` or to get every frame as blob efficiently so that it could be processed?

This is really expensive `capturedImage.takePhoto()`

**Comment by developer239** [comment] 2018-01-14 20:23
This is what I ended up doing:

```
}).then((stream) => {
        const video = document.createElement('video');
        video.srcObject = stream;
        video.onloadedmetadata = () => {
          video.play();
          setInterval(() => {
            const canvas = document.createElement('canvas');
            canvas.getContext('2d').drawImage(video, 0, 0, 800, 800);
            canvas.toBlob(blob => {
              toBuffer(blob, function (err, buffer) {
                if (err) throw err;
                // do some magic with buffer
              });
            });
          }, 40);
        };
```

**Comment by AJLoveChina** [comment] 2020-03-17 06:42
> This is what I ended up doing. It is actually a lot more performant.
> 
> ```
>       }).then((stream) => {
>         const video = document.createElement('video');
>         video.srcObject = stream;
>         video.onloadedmetadata = () => {
>           video.play();
>           setInterval(() => {
>             const canvas = document.createElement('canvas');
>             canvas.getContext('2d').drawImage(video, 0, 0, 800, 800);
>             canvas.toBlob(blob => {
>               toBuffer(blob, function (err, buffer) {
>                 if (err) throw err;
>                 // do some magic with buffer
>               });
>             });
>           }, 40);
>         };
> ```

I try your advice, but it is not more performant. In my test page:
* ImageCapture + grabFrame  => 21 FPS
* video + canvas + getImageData => 88 FPS

but your advice 
* video + canvas + toBlob + toArrayBuffer => only 8 FPS

So why do you say better performance?

**Comment by jrichardsz** [comment] 2023-01-15 22:54
This worked for me https://stackoverflow.com/a/75128936/3957754
