### ISSUE TITLE
getPhotoCapabilities vs getCapabilities

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/mediacapture-image#143] opened 2017-01-11 10:56 UTC
from @w3ctag 's [review](https://github.com/w3ctag/spec-reviews/issues/133#issuecomment-270259285) @travisleithead:
> Seems like 'getPhotoCapabilities' and the MediaStreamTrack's 'getCapabilities' are nearly the same. Is there a reason to have the separate method and property list?

**Comment by miguelao** [comment] 2017-01-11 17:51
#124 is tracking the use of `ConstrainablePattern` in IC, this comment is a duplicate of it.

**Closed by miguelao** 2017-01-11 17:51 UTC
